### ISSUE TITLE
Text is wrong on Kioko

### ISSUE THREAD

**Issue by ZucriyAmsuna** [zephyrfalcon/mnsearch-react#1]
Kioko's Effect - Demotivate has a wrong word. You have this:

> Once per turn, when one of your Creatures is attacked, you may have the attacked Creature remove energy equal to its starting energy instead of its current energy.

But it should be this:

> Once per turn, when one of your Creatures is attacked, you may have the **attacking** Creature remove energy equal to its starting energy instead of its current energy.

**Comment by zephyrfalcon** [comment]
All done... 

(As I recall, I created `.yaml` files with the card info by hand, long ago (like 10+ years ago, for the previous incarnation(s) of this search)... so it's quite possible that there will be more typos hidden somewhere.)
