### ISSUE TITLE
Search only cards with MRP

### ISSUE THREAD

**Issue by willieThibault** [zephyrfalcon/mnsearch-react#11]
There does not seem to currently be a way to filter for cards with an MRP. Is that a feature that could be added?

**Comment by zephyrfalcon** [comment]
As in, show all cards that have MRP data? Or do you want to be able to search the MRP data? (That might not be much different from the original data in most cases...)

**Comment by willieThibault** [comment]
Much like there are checkboxes to filter down by Region, Set, Type, etc., I'd like to be able to make a list of only MRP cards or no MRP cards.

**Comment by zephyrfalcon** [comment]
I have a new version up that supports this... I _think_ it works... but it's kinda hard to tell for sure, due to the, um, idiosyncrasies of web programming. It's live at http://magi-nation-search.pingoland.xyz/, let me know what you think.

**Comment by willieThibault** [comment]
Yes, this is what I was asking for! Thanks for that!

**Comment by zephyrfalcon** [comment]
No problem!
